import { useEffect, useRef, useState } from 'react';
import { motionClips } from '../data/content';
import Lightbox from './Lightbox';
import './MotionClipGrid.css';

const prefersReducedMotion = () =>
    typeof window !== 'undefined' &&
    Boolean(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches);

/** Generated by scripts/build-images.mjs for videos and GIFs alike. */
const posterFor = (clip) => clip.poster ?? clip.src.replace(/\.\w+$/, '-poster.webp');

/**
 * Inline, self-hosted 2D movement loops.
 *
 * Clips loop muted so the movement is visible without a click or YouTube
 * chrome. Playback is driven by an IntersectionObserver so off-screen clips
 * stay paused, and autoplay is skipped entirely for visitors who prefer
 * reduced motion — they get the poster frame and standard controls instead.
 *
 * The loops repeat indefinitely, so a Pause motion toggle stops every clip in
 * the grid at once (WCAG 2.2.2). GIFs cannot be paused, so paused GIFs swap
 * to their poster still.
 */
function MotionClipGrid({ featuredOnly = false }) {
    const [selected, setSelected] = useState(null);
    const [paused, setPaused] = useState(prefersReducedMotion);
    const gridRef = useRef(null);
    const clips = featuredOnly
        ? motionClips.filter((clip) => clip.featured)
        : motionClips;

    useEffect(() => {
        if (!gridRef.current) return;
        const videos = gridRef.current.querySelectorAll('video');
        if (!videos.length) return;
        if (paused) {
            videos.forEach((video) => video.pause());
            return;
        }

        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.play().catch(() => { });
                    } else {
                        entry.target.pause();
                    }
                });
            },
            { threshold: 0.25 }
        );
        videos.forEach((video) => observer.observe(video));
        return () => observer.disconnect();
    }, [paused]);

    const renderMedia = (clip, enlarged) =>
        clip.type === 'video' ? (
            <video
                src={clip.src}
                /* Generated by scripts/build-images.mjs; without it the clip
                   is a black rectangle until playback starts. */
                poster={posterFor(clip)}
                autoPlay={enlarged && !prefersReducedMotion()}
                muted
                loop
                playsInline
                preload="metadata"
                controls={enlarged || prefersReducedMotion()}
                aria-label={clip.title}
            />
        ) : (
            <img
                src={paused && !enlarged ? posterFor(clip) : clip.src}
                alt={`${clip.title}. ${clip.caption}`}
                loading="lazy"
            />
        );

    return (
        <>
            <button
                type="button"
                className="jm-button jm-button--quiet jm-clips__toggle"
                onClick={() => setPaused((value) => !value)}
            >
                {paused ? 'Play motion' : 'Pause motion'}
            </button>
            <div ref={gridRef} className="jm-clips">
                {clips.map((clip) => (
                    <figure key={clip.id} className="jm-clip">
                        <button
                            type="button"
                            className="jm-clip__trigger"
                            onClick={() => setSelected(clip)}
                            aria-label={`Enlarge ${clip.title}`}
                        >
                            {renderMedia(clip, false)}
                            <span className="jm-clip__expand" aria-hidden="true">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                    strokeWidth="2" strokeLinecap="round">
                                    <path d="M9 3H3v6M15 3h6v6M9 21H3v-6M15 21h6v-6" />
                                </svg>
                            </span>
                        </button>
                        <figcaption className="jm-clip__caption">
                            {/* h3, not h4: the grid always sits directly under a
                                section h2, and skipping a level breaks heading
                                order for anyone navigating by headings. */}
                            <h3 className="jm-clip__title">{clip.title}</h3>
                            <p className="jm-clip__text">{clip.caption}</p>
                            {clip.meta && <p className="jm-clip__meta">{clip.meta}</p>}
                        </figcaption>
                    </figure>
                ))}
            </div>

            {selected && (
                <Lightbox
                    label={`${selected.title}, clip viewer`}
                    onClose={() => setSelected(null)}
                    caption={
                        <>
                            <h3 className="jm-lightbox__title">{selected.title}</h3>
                            <p className="jm-lightbox__description">{selected.caption}</p>
                            {selected.meta && (
                                <span className="jm-lightbox__meta">{selected.meta}</span>
                            )}
                        </>
                    }
                >
                    {renderMedia(selected, true)}
                </Lightbox>
            )}
        </>
    );
}

export default MotionClipGrid;
